### ISSUE TITLE
Not able to bring up the container after building the MariaDB Docker image.

### ISSUE THREAD

**Issue by gopinathkarangula** [mariadb-corporation/MariaDB-ES-Docker#1]
MariaDB Enterprise Server                        74  B/s | 109  B     00:01
Errors during downloading metadata for repository 'mariadb-es-main':
  - Status code: 404 for https://dlm.mariadb.com/repo/bxxxx/mariadb-enterprise-server/10.5.8/rpm/rhel/8/x86_64/repodata/repomd.xml 
Error: Failed to download metadata for repo 'mariadb-es-main': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

**Comment by abychko** [comment]
bxxxx is not a valid token
