### ISSUE TITLE
entrypoint is completely relaunch at each start !

### ISSUE THREAD

**Issue by rusher** [mariadb-corporation/MariaDB-ES-Docker#5]
Entrypoint script runs completly at each start. 
First run will be ok. 
after restart / stop-start, there will be a lot of issues, like since MARIADB_USER now exists, if will fails. 
if root as a random generated pwd, next validation will fail : 
```
[Init message]: Bringing up MariaDB Enterprise Server 10.5...
[Warning] Access denied for user 'root'@'localhost' (using password: NO)
```

**Comment by abychko** [comment]
confirmed, there is a marker file /es-init.completed to prevent this, but no check is implemented. will fix

**Comment by abychko** [comment]
fixed
